djparser/urls.py
from django.urls import path
from . import views

app_name = 'djparser'

urlpatterns = [
    path('',views.index,name='index'),
    path('delete/<int:sid>/',views.delete,name='delete'),
    path('result/<int:sid>/',views.result,name='result'),
    path('parse/<int:sid>/',views.parse,name='parse'),
    path('setting/',views.setting,name='setting')
]

webparse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('djparser.urls'))
]

djparser/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Site(models.Model):
    url = models.CharField(max_length=255)
    query = models.CharField(max_length=255)
    pub_date = models.DateTimeField(default=timezone.now)

class Node(models.Model):
    site = models.ForeignKey(Site,on_delete=models.CASCADE)
    val = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)

djparser/forms.py
from django import forms

class SiteForm(forms.Form):
    url = forms.URLField(label='URL страницы',max_length=255)
    query = forms.CharField(label='Запрос XPath',max_length=255)

djparser/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Site,Node
from .forms import SiteForm
from .parse import parser
import json

# Create your views here.
def index(request):
    if request.method == 'GET':
        form = SiteForm()
        sites = Site.objects.order_by('-pub_date').all()
        return render(request,'index.html',{'sites' : sites,'form' : form})
    else:
        sites = Site.objects.order_by('-pub_date').all()
        form = SiteForm(request.POST)
        if form.is_valid():
            site = Site.objects.create(**form.cleaned_data)
            site.save()
            return redirect(reverse('djparser:index'))
        else:
            return render(request,'index.html',{'sites' : sites,'form' : form, 'err' : form.errors})

def delete(request,sid):
    site = get_object_or_404(Site,pk = sid)
    Node.objects.filter(site=site).delete()
    site.delete()
    return redirect(reverse('djparser:index'))

def parse(request,sid):
    site = get_object_or_404(Site,pk = sid)
    pobj = json.load(open('parser.json'))
    try:
        res = parser(site.url,site.query,pobj['headers'],pobj['proxies'])
    except Exception as e:
        form = SiteForm()
        sites = Site.objects.order_by('-pub_date').all()
        return render(request,'index.html',{'sites' : sites,'form' : form, 'err' : e})
    nodes = Node.objects.filter(site=site).all()
    vals = [n.val for n in nodes]
    inf = []
    for i in res:
        if i not in vals:
            node = Node.objects.create(site=site,val=i)
            node.save()
            inf.append(i)
    return render(request,'parser.html',{'site' : site,'res' : inf })

def result(request,sid):
    site = get_object_or_404(Site,pk = sid)
    res = Node.objects.filter(site=site).order_by('-pub_date').all()
    inf = [r.val for r in res]
    print(len(inf))
    pag = Paginator(inf,10)
    if 'page' in request.GET:
        page = request.GET['page']
    else:
        page = 1
    inf = pag.get_page(page)
    return render(request,'result.html',{'site' : site,'res' : inf })

def setting(request):
    try:
        pobj = json.load(open('parser.json'))
    except OSError:
        pobj = {
            "headers" : {
                "User-Agent" : "",
                "Cookie" : ""
            },
            "proxies" : {
                "http" : "",
                "https" : ""
            }
        }
        json.dump(pobj,open('parser.json','w'))
    ans = {
        'agent' : pobj['headers']['User-Agent'],
        'cookie' : pobj['headers']['Cookie'],
        'http' : pobj['proxies']['http'],
        'https' : pobj['proxies']['https'],
    }
    if request.method == "GET":
        return render(request,'setting.html',ans)
    else:
        pobj['headers']['User-Agent'] = request.POST['User-Agent']
        pobj['headers']['Cookie'] = request.POST['Cookie']
        pobj['proxies']['http'] = request.POST['http']
        pobj['proxies']['https'] = request.POST['https']
        json.dump(pobj,open('parser.json','w'))
        ans = {
            'agent' : pobj['headers']['User-Agent'],
            'cookie' : pobj['headers']['Cookie'],
            'http' : pobj['proxies']['http'],
            'https' : pobj['proxies']['https'],
            'ok' : 'Данные парсера обновлены'
        }
        return render(request,'setting.html',ans)

djparser/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django Parser</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'djparser:index' %}">Django Parser</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'djparser:setting' %}">Настройки парсера</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          {% block 'content' %}
          {% endblock %}
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

djparser/templates/index.html
{% extends 'base.html' %}
{% block 'content' %}
  <h1 class="mt-5">Список URL для парсинга</h1>
  {% if err %}
  <div class="alert alert-danger">
    {{ err }}
  </div>
  {% endif %}
  <form method="POST">
    {% csrf_token %}
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">URL запрос</span>
      </div>
      <input type="text" name="url" value="" class="form-control" aria-describedby="basic-addon1">
    </div>
    <br>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon2">XPath выражение</span>
      </div>
      <input type="text" name="query" value="" class="form-control" aria-describedby="basic-addon2">
    </div>
    <br>
    <input type="submit" value="Добавить" class="btn btn-primary">
  </form>
  <br>
  <table class="table table-dark">
    <tr>
      <th>URL</th>
      <th>Запрос</th>
      <th>Действие</th>
    </tr>
  {% for site in sites %}
    <tr>
      <td>{{site.url}}</td>
      <td>{{site.query}}</td>
      <td><a href="{% url 'djparser:parse' site.pk %}">Парсить</a>
        <a href="{% url 'djparser:result' site.pk %}">Результат</a>
        <a href="{% url 'djparser:delete' site.pk %}">Удалить</a></td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

djparser/templates/parser.html
{% extends 'base.html' %}
{% block 'content' %}
  <h1 class="mt-5">{{site.url}}</h1>
  <br>
  <table class="table table-dark">
  {% for i in res %}
    <tr>
      <td>{{i}}</td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

djparser/templates/result.html
{% extends 'base.html' %}
{% block 'content' %}
  <h1 class="mt-5">{{site.url}}</h1>
  <br>
  <table class="table table-dark">
  {% for i in res %}
  <tr>
    <td>{{i}}</td>
  </tr>
  {% endfor %}
  </table>
  <ul class="pagination">
    {% if res.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{res.previos_page_number}}">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% endif %}
    <li class="page-item active">
      <a class="page-link" href="#">{{res.number}}<span class="sr-only">(current)</span></a>
    </li>
    {% if res.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{res.paginator.num_pages}}">{{res.paginator.num_pages}}</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{res.next_page_number}}">Next</a>
    </li>
    {% endif %}
  </ul>
{% endblock %}

djparser/templates/setting.html
{% extends 'base.html' %}
{% block 'content' %}
<h1 class="mt-5">Настройки парсера</h1>
{% if ok %}
<div class="alert alert-success">
  {{ok}}
</div>
{% endif %}
<form method="POST">
  {% csrf_token %}
  <h3>Заголовки:</h3>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">User-Agent:</span>
      </div>
      <input type="text" name="User-Agent" value="{{ agent }}" class="form-control" aria-describedby="basic-addon1">
    </div>
    <br>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon2">Cookie:</span>
      </div>
      <input type="text" name="Cookie" value="{{ cookie }}" class="form-control" aria-describedby="basic-addon2">
    </div>
    <br>
  <h3>Прокси:</h3>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon3">HTTP:</span>
    </div>
    <input type="text" name="http" value="{{ http }}" class="form-control" aria-describedby="basic-addon3">
  </div>
  <br>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon4">HTTPS:</span>
    </div>
    <input type="text" name="https" value="{{ https }}" class="form-control" aria-describedby="basic-addon4">
  </div>
  <br>
  <input type="submit" value="Сохранить" class="btn btn-primary">
</form>
{% endblock %}